### ISSUE TITLE
What's the password?

### ISSUE THREAD

**Issue by injetk** [mojtaba1377/InstaBruteForcer#1]
![image](https://cloud.githubusercontent.com/assets/16195172/17217357/fefd7dcc-54db-11e6-991c-260ccfb2f4d8.png)
am I missing something? xd

**Comment by mojtaba1377** [comment]
Please Try to download New Version of This Program. I Updated it 26 min ago.

**Comment by injetk** [comment]
I am still prompt with
![image](https://cloud.githubusercontent.com/assets/16195172/17344996/0b419cca-58fc-11e6-92cf-901a6a3c56d2.png)
are you sure you're not setting a password on the second zip file?

**Comment by mojtaba1377** [comment]
the pass is : github.com
